version: '3'

services:
  web:
    image: csunmetalab/environment:csumetro
    container_name: ${COMPOSE_PROJECT_NAME}_web
    restart: always
    ports:
      - '${WEB_PORT}:80'
    volumes:
      - .:/var/www/
    links:
      - db

  # Installs composer
  composer:
    image: composer:2.0.8
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    restart: 'no'
    command: install
    volumes:
      - .:/app/

  # Adminer server
  adminer:
    image: adminer:4.8.0
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: always
    ports:
      - ${ADMIR_PORT}:8080

  # Database server
  db:
    image: mysql:5.6.41
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql/


volumes:
    db_data:
      name: ${COMPOSE_PROJECT_NAME}_volume