version: '3'

services:
  webserver:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: csunmetalab/environment:csumetro
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/
    links:
      - db

  # Installs composer
  composer:
    restart: 'no'
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    image: composer:latest
    command: install
    volumes:
      - .:/app/

  # Adminer server
  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # Database server
  db:
    image: mysql:5.6.41
    container_name: ${COMPOSE_PROJECT_NAME}_database
    volumes:
      - db_data:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
    db_data:
      name: ${COMPOSE_PROJECT_NAME}_volume